# Generated by Django 3.2.13 on 2022-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuisine",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
